name: Sample Book Application Workflow

on:
  push:
    branches: ["main", "github_workflows"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Building of node application is starting.."
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Deployment to DEV has started.."
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started.."
  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Deployment to STG has started.."
  test-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started.."
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Deployment to PRD has started.."
  test-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started.."