name: Sample Book Application Workflow

on:
  push:
    branches: ["main", "github_workflows"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'DEV'
          port: '1010'
  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/api-automation'
          ref: 'books_tests'
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started.."
      - name: Install all dependencies
        run: npm install
      - name: Run API tests
        run: npm run BOOKS BOOKS_DEV
  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'STG'
          port: '2020'
  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started.."
  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'PRD'
          port: '3030'
  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started.."