name: Sample Book Application Workflow

on:
  push:
    branches: ["main", "github_workflows"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Building of node application is starting.."
      - name: Install all dependencies
        run: npm install
  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to DEV has started.."
      - name: Install all dependencies
        run: npm install
      - name: Delete existing pm2 service
        run: pm2 delete "books-DEV" || exit 0
      - name: Run sample-book-app pm2 service
        run: pm2 start -n "books-DEV" index.js -- 1010
  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started.."
  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to STG has started.."
  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started.."
  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to PRD has started.."
  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started.."